export default function () {
  return {
    // NEW
    read_supcus_all: {},
    pomain: [],
    pomain_status: {},
    read_po_by_refno: {},
    pochild: [],
    pochild_status: {},
    read_location_list: {},
    search_item_for_po: {},
    get_item_by_itemcode_for_po: {},
    grmain: [],
    grmain_status: {},
    read_gr_by_refno: {},
    grchild: [],
    grchild_status: {},
    read_po_list_for_convert_gr: [],
    simple_receive: {},
    posting_po: {},
    unposting_po: {},
    posting_gr: {},
    unposting_gr: {},
    posting_dn: {},
    unposting_dn: {},
    dn: [],
    get_dn_v2: [],
    dn_status: {},
    read_dn_by_refno: {},
    dnchild: [],
    dnchild_status: {},
    invoice: {},
    ibt: [],
    ibt_status: [],
    read_ibt_by_refno: {},
    ibtchild: [],
    ibtchild_status: {},
    search_supcus: [],
    read_po_supplier_list: [],
    item_tagging: {},
    item_untagging: {},
    read_barcode_by_itemcode: {},
    cn: [],
    cn_status: {},
    read_cn_by_refno:{},
    posting_cn: {},
    unposting_cn: {},
    cnchild: [],
    cnchild_status: {},
    read_pochild: {},
    runscript_multi_status:{},
    surcharge_discount_list:[],
    search_item_for_dn: {},
    search_item_for_cn: {},
    bulk_create_pochild_status:{},
    grn_item_tagging_status:{},
    grn_item_untagging_status:{},
    surcharge_discount:[],
    surcharge_discount_status:{},
    grn_create_grchild_status:{},
    gst_read_gst:[],
    read_master_code_by_trans_type:[]
  }
}
