export default function () {
  return {
    // NEW
    read_supcus_all: {},
    itemmaster: [],
    item_status: {},
    all_code_list:[],
    dept_list: [],
    sub_dept_list: [],
    category_list:[],
    manufacturer_list:[],
    brand_list:[],
    origin_list:[],
    item_color_list:[],
    item_size_list:[],
    item_type_list:[],
    read_master_code_by_trans_type:[],
    read_item:{},
    read_barcode_by_itemcode:{},
    read_po_by_refno: {},
    pochild: [],
    pochild_status: {},
    read_location_list: {},
    search_item_for_po: {},
    get_item_by_itemcode_for_po: {},
    barcode_status:{},
    read_tax:[],
    read_gst:[],
    itemmaster_branch_stock:[],
    supplier_item_list:[],
    itemmastersupcode_status:{},
    create_item_new: {},
    manufacturer_list_new: [],
    read_barcode_by_itemcode_new: {},
    set_group_dept: {},
    read_supcus_link:{},
    read_itemmaster_miscellaneous: {},
    read_itemmaster_listed_branch:{},
    read_itemmaster_itemtype: {},
    read_itemmaster_pricetype: {},
    read_itemmaster_replenishment:{},
    read_itemmaster_block_by_branch: {},
    read_price_change_req: {},
    read_price_change_req2item: {},
    read_cost_price_change_item: {},
    read_cost_price_change_item_vendor: {},
    read_grchild: {},
    read_itemmaster_discount: {},
    read_itemmaster_price_break: {},
    read_itemmaster_price_break_c : {},
    read_cp_set_branch: {},
    read_master_code_transtype: {},
    read_item_all: {},
    read_req_chg_category: {},
    read_req_chg_category_c: {},
    read_itemmaster_branch_stock: {},
    read_simain: {},
    read_sichild: [],
    read_supcus_dropdown: {},
    read_purchase_promo: {},
    read_purchase_promo_c: {},
    excel_download_itemmaster: {},
    excel_upload_itemmaster: {},
    read_posmain: {},
    read_gr: {},
    read_promo_supplier: {},
    read_promo_supplier_c: {},
    read_locationstock_period: {},
    read_locationstock_groupby_location: {},
    read_locationstock_groupby_location_group: {},
    read_set_assorted_item: {},
    read_set_assorted_item_c: {},
    read_price_change_req1loc: {},
    read_po_new: {},
    read_po_by_itemcode: {},
    read_itemmaster_othersinfo: {},
    itemmaster_othersinfo_status: {},
    read_table_total_row: {},
    read_custom_dropdown_all: {},
    get_photo: {},
    upload_photo_status: {},
    get_poschild: {},
 }
}
